name: Erlang CI

on:
  push:
    branches: [ develop-3.0 ]
  pull_request:
    branches: [ develop-3.0 ]


jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        otp:
          - "22.3.4.24"

    container:
      image: erlang:${{ matrix.otp }}

    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v2
      - name: Compile
        run: ./rebar3 compile
      - name: Run xref, dialyzer and eunit
        run: ./rebar3 do xref, dialyzer, eunit
